<?php
$security_code=array();
$security_code[]=array(
"question"=>"1+3",
"answer"=>"4"
);
$security_code[]=array(
"question"=>"2+3",
"answer"=>"5"
);
$security_code[]=array(
"question"=>"3+3=",
"answer"=>"6"
);
$security_code[]=array(
"question"=>"4+3=",
"answer"=>"7"
);
$security_code[]=array(
"question"=>"5+3=",
"answer"=>"8"
);
$security_code[]=array(
"question"=>"1*3=",
"answer"=>"3"
);
$security_code[]=array(
"question"=>"2*3=",
"answer"=>"6"
);
$security_code[]=array(
"question"=>"3*3=",
"answer"=>"9"
);
$security_code[]=array(
"question"=>"4*3=",
"answer"=>"12"
);
$security_code[]=array(
"question"=>"5*3=",
"answer"=>"15"
);
$security_code[]=array(
"question"=>"10-1=",
"answer"=>"9"
);
$security_code[]=array(
"question"=>"10-2=",
"answer"=>"8"
);
$security_code[]=array(
"question"=>"10-3=",
"answer"=>"7"
);
$security_code[]=array(
"question"=>"10-4=",
"answer"=>"6"
);
$security_code[]=array(
"question"=>"10-5=",
"answer"=>"5"
);
$security_code[]=array(
"question"=>"45+5=",
"answer"=>"50"
);
$security_code[]=array(
"question"=>"100-55=",
"answer"=>"45"
);
$security_code[]=array(
"question"=>"99+2=",
"answer"=>"101"
);
$security_code[]=array(
"question"=>"65-7=",
"answer"=>"58"
);
$security_code[]=array(
"question"=>"23-9=",
"answer"=>"14"
);
?>