<?php
/////////////////////////////////////////////////////////////////////////
// xBtit - Bittorrent tracker/frontend
//
// Copyright (C) 2004 - 2007  Btiteam
//
//    This file is part of xBtit.
//
//    xBtit is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    xBtit is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with xBtit.  If not, see <http://www.gnu.org/licenses/>.
//
/////////////////////////////////////////////////////////////////////////

$smilies = array(
  ":)" => "smile1.gif",
  ";)" => "wink.gif",
  ":D" => "grin.gif",
  ":P" => "tongue.gif",
  ":(" => "sad.gif",
  ":'(" => "cry.gif",
  ":|" => "noexpression.gif",
  ":-/" => "confused.gif",
  ":-O" => "ohmy.gif",
  "8)" => "cool1.gif",
  "O:-" => "angel.gif",
  "-_-" => "sleep.gif",
  ":grrr:" => "angry.gif",
  ":smile:" => "smile2.gif",
  ":lol:" => "laugh.gif",
  ":cool:" => "cool2.gif",
  ":fun:" => "fun.gif",
  ":thumbsup:" => "thumbsup.gif",
  ":thumbsdown:" => "thumbsdown.gif",
  ":blush:" => "blush.gif",
  ":weep:" => "weep.gif",
  ":unsure:" => "unsure.gif",
  ":closedeyes:" => "closedeyes.gif",
  ":yes:" => "yes.gif",
  ":no:" => "no.gif",
  ":love:" => "love.gif",
  ":?:" => "question.gif",
  ":!:" => "excl.gif",
  ":idea:" => "idea.gif",
  ":arrow:" => "arrow.gif",
  ":hmm:" => "hmm.gif",
  ":huh:" => "huh.gif",
  ":w00t:" => "w00t.gif",
  ":geek:" => "geek.gif",
  ":look:" => "look.gif",
  ":rolleyes:" => "rolleyes.gif",
  ":kiss:" => "kiss.gif",
  ":shifty:" => "shifty.gif",
  ":blink:" => "blink.gif",
  ":smartass:" => "smartass.gif",
  ":sick:" => "sick.gif",
  ":crazy:" => "crazy.gif",
  ":wacko:" => "wacko.gif",
  ":alien:" => "alien.gif",
  ":wizard:" => "wizard.gif",
  ":wave:" => "wave.gif",
  ":wavecry:" => "wavecry.gif",
  ":baby:" => "baby.gif",
  ":ras:" => "ras.gif",
  ":sly:" => "sly.gif",
  ":devil:" => "devil.gif",
  ":evil:" => "evil.gif",
  ":evilmad:" => "evilmad.gif",
  ":yucky:" => "yucky.gif",
  ":nugget:" => "nugget.gif",
  ":sneaky:" => "sneaky.gif",
  ":smart:" => "smart.gif",
  ":shutup:" => "shutup.gif",
  ":shutup2:" => "shutup2.gif",
  ":yikes:" => "yikes.gif",
  ":flowers:" => "flowers.gif",
  ":wub:" => "wub.gif",
  ":osama:" => "osama.gif",
  ":saddam:" => "saddam.gif",
  ":santa:" => "santa.gif",
  ":indian:" => "indian.gif",
  ":guns:" => "guns.gif",
  ":crockett:" => "crockett.gif",
  ":zorro:" => "zorro.gif",
  ":snap:" => "snap.gif",
  ":beer:" => "beer.gif",
  ":drunk:" => "drunk.gif",
  ":sleeping:" => "sleeping.gif",
  ":mama:" => "mama.gif",
  ":pepsi:" => "pepsi.gif",
  ":medieval:" => "medieval.gif",
  ":rambo:" => "rambo.gif",
  ":ninja:" => "ninja.gif",
  ":hannibal:" => "hannibal.gif",
  ":party:" => "party.gif",
  ":snorkle:" => "snorkle.gif",
  ":evo:" => "evo.gif",
  ":king:" => "king.gif",
  ":chef:" => "chef.gif",
  ":mario:" => "mario.gif",
  ":pope:" => "pope.gif",
  ":fez:" => "fez.gif",
  ":cap:" => "cap.gif",
  ":cowboy:" => "cowboy.gif",
  ":pirate:" => "pirate.gif",
  ":rock:" => "rock.gif",
  ":cigar:" => "cigar.gif",
  ":icecream:" => "icecream.gif",
  ":oldtimer:" => "oldtimer.gif",
  ":wolverine:" => "wolverine.gif",
  ":strongbench:" => "strongbench.gif",
  ":weakbench:" => "weakbench.gif",
  ":bike:" => "bike.gif",
  ":music:" => "music.gif",
  ":book:" => "book.gif",
  ":fish:" => "fish.gif",
  ":whistle:" => "whistle.gif",
  ":stupid:" => "stupid.gif",
  ":dots:" => "dots.gif",
  ":axe:" => "axe.gif",
  ":hooray:" => "hooray.gif",
  ":yay:" => "yay.gif",
  ":cake:" => "cake.gif",
  ":hbd:" => "hbd.gif",
  ":hi:" => "hi.gif",
  ":offtopic:" => "offtopic.gif",
  ":band:" => "band.gif",
  ":hump:" => "hump.gif",
  ":punk:" => "punk.gif",
  ":bounce:" => "bounce.gif",
  ":group:" => "group.gif",
  ":console:" => "console.gif",
  ":smurf:" => "smurf.gif",
  ":spidey:" => "spidey.gif",
  ":smurf:" => "smurf.gif",
  ":rant:" => "rant.gif",
  ":pimp:" => "pimp.gif",
  ":nuke:" => "nuke.gif",
  ":judge:" => "judge.gif",
  ":jacko:" => "jacko.gif",
  ":ike:" => "ike.gif",
  ":greedy:" => "greedy.gif",
  ":dumbells:" => "dumbells.gif",
  ":clover:" => "clover.gif",
  ":shit:" => "shit.gif",
  ":beer1:" => "beer1.gif",
  ":bmkid:" => "bmkid.gif"
);

$privatesmilies = array(
  ":-)" => "smile1.gif",
  ";-)" => "wink.gif",
  ":-D" => "grin.gif",
  ":-P" => "tongue.gif",
  ":-(" => "sad.gif",
  ":Boozer:" => "alcoholic.gif",
  ":spank:" => "spank.gif"
);
?>